<a href="https://colab.research.google.com/github/soorimoh/lab0-soorimoh/blob/master/Laboratory_2_soorim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory #2

* Name: Soorim Oh
* Student ID: 202021104

Answer the questions or complete the tasks below, use the specific method described if applicable.

**What is 9 to the power of 6?**

In [1]:
9**6

531441

**Split this string:**

    st = "Modeling of Estimation for Weather Change!"
    
**into a list.**

In [2]:
st = "Modeling of Estimation for Weather Change!"

In [3]:
st.split(" ")

['Modeling', 'of', 'Estimation', 'for', 'Weather', 'Change!']

**Given the variables:**

    space_station = "Death Star I"
    diameter = 120

**Use .format() to print the following string:**

    The diameter of Death Star I is 120 kilometers.

In [4]:
space_station = "Death Star I"
diameter = 120

In [5]:
print("The diameter of ", end = space_station)
print(" is 120 kilometers", end = ".")

The diameter of Death Star I is 120 kilometers.

**Given this nested list, use indexing to grab the word "Weather Change!"**

In [6]:
lst = [12,13,[14,15],[16,[17,18,['Weather Change!']],19,20],21,22]

In [7]:
lst[3][1][2][0]

'Weather Change!'

**Given this nest dictionary grab the word "Weather Change!". Be prepared, this will be annoying/tricky**

In [8]:
d = {'key1':[1,2,3,{'key1_1':['Modeling','of','Estimation',{'key1_2':[1,2,3,'Weather Change!']}]}]}

In [9]:
d['key1'][3]['key1_1'][3]['key1_2'][3]

'Weather Change!'

** What is the main difference between a tuple and a list?**

In [10]:
# Tuple is immutable

**Create a function that grabs the user id from an email address from a string in the form:**

    user@domain.com
    
**So for example, passing "user@domain.com" would return: user**

In [11]:
def userGet(email):
  return email.split('@')[0]

In [12]:
userGet('user@domain.com')

'user'

**Create a basic function that returns True if the word 'weather' is contained in the input string. ('weather' or 'Weather')**

In [13]:
def findWeather(st):
  return 'weather' in st.lower().split()

In [14]:
findWeather('Is there a Weather in this sentence?')

True

**Create a function that counts the number of times the word "weather" occurs in a string. Ignore edge cases.**

In [15]:
def countWeather(st):
  count = 0
  for word in st.lower().split():
    if word == 'weather':
      count += 1
  return count

In [16]:
countWeather('This weather is better than the weather of yesterday!')

2

**Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 'w'. For example:**

    seq = ['dog','apple','word','weather','funny']

**should be filtered down to:**

    ['word','weather']

In [17]:
seq = ['dog','apple','word','weather','funny']

In [18]:
list(filter(lambda word: word[0]=='w',seq))

['word', 'weather']

**Write a Python function to reverse a string**

    s = '1234567890abcdefghijk' 

**should be shown:**

    'kjihgfedcba0987654321'

In [19]:
def string_reverse(str):
  rstr = ''
  index = len(str)
  while index > 0:
      rstr += str[index -1]
      index = index -1
  return rstr
print(string_reverse)

<function string_reverse at 0x7f8e82ae76a8>


In [20]:
s = '1234567890abcdefghijk'
string_reverse(s)

'kjihgfedcba0987654321'

In [21]:
string_reverse('RADAR')

'RADAR'

In [22]:
string_reverse('Laboratory 2')

'2 yrotarobaL'

# You finished your laboratory. Congratulations!~

### Numpy
Install : conda install numpy pip install numpy



In [23]:
import numpy as np

## Numpy Arrays
Vectors, arrays, matrices, and number generation
Numpy arrays : vectors and matrices.
Vectors: 1-d arrays
Matrices: 2-d arrays

### Creating Numpy Arrays

In [24]:
my_list = [1,2,3,4]

In [25]:
print(my_list)

[1, 2, 3, 4]


In [26]:
np.array(my_list)

array([1, 2, 3, 4])

In [27]:
my_matrix = [(1,2,3),(4,5,6),(7,8,9)] # 3x3
print(my_matrix)

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]


In [28]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.reshape(4,4)

NameError: ignored

## Built-in Methods
### arange
Return evenly spaced values within a given interval.

In [32]:
np.arange(0,10)    #[0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [34]:
### zeros and ones

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Returns evenly spaced numbers over a specified interval

In [39]:
np.linspace(0,10,3)    #[0,10]

array([ 0.,  5., 10.])

In [40]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [41]:
np.linspace(0,16,16)

array([ 0.        ,  1.06666667,  2.13333333,  3.2       ,  4.26666667,
        5.33333333,  6.4       ,  7.46666667,  8.53333333,  9.6       ,
       10.66666667, 11.73333333, 12.8       , 13.86666667, 14.93333333,
       16.        ])

### eye

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
### rand

In [43]:
np.random.rand(2)    #[0,1)

array([0.78436643, 0.99950577])

In [44]:
np.random.rand(5,5)

array([[0.80012355, 0.48305277, 0.454448  , 0.80120099, 0.02714308],
       [0.94580648, 0.85146931, 0.87865586, 0.05737945, 0.8338544 ],
       [0.61479539, 0.29289453, 0.63404079, 0.21955086, 0.28321158],
       [0.35115162, 0.26018458, 0.46981452, 0.28851759, 0.45493416],
       [0.35776003, 0.28540883, 0.56266107, 0.1389113 , 0.73983795]])

### randint

In [45]:
np.random.randint(1,1000)  #[1,100)

730

In [46]:
np.random.randint(1,100,10)

array([94, 68, 34, 19, 82, 42, 48, 39, 14, 11])